export const items = [
    {
        image: require('../assets/plantas_exterior/Eugenia_XL.jpg'),
        imageAlt: 'Eugenia-XL',
        name: 'Eugenia - XL',
        categoryId: 1,
        price: 999,
        description: 'La Eugenia es un arbusto o árbol de hojas brillantes que suele utilizarse como cerco vivo o en maceta de manera decorativa, dada su versatilidad al podarlo y darle formas a medida. Las hojas son brillantes y ovaladas, con hojas nuevas que llegan con un tono rojizo y cambian a verde a medida que envejecen.',
        amount:0,
        stock: 10,
        id: 0
    },
    {
        image: require('../assets/plantas_exterior/Duranta_M.jpg'),
        imageAlt: 'Duranta–M',
        name: 'Duranta – M',
        categoryId: 1,
        price: 999,
        description: 'Son arbustos perennes (follaje todo el año). Tienen hojas de color verde/amarillo intenso. Las flores aparecen en racimos y pueden ser blancas, azules, lilas o violetas. Florecen en primavera y verano.',
        amount:0,
        stock: 10,
        id: 1
    },
    {
        image: require('../assets/plantas_exterior/Buxus_XL.jpg'),
        imageAlt: 'Buxus-XL',
        name: 'Buxus - XL',
        categoryId: 1,
        price: 999,
        description: 'Es un arbusto muy resistente, pudiéndose podar para tener en forma, o se puede dejar crecer como pequeño arbolito de un metro y medio o dos de altura. Se caracteriza por tener un ritmo de crecimiento lento y unas hojas muy pequeñas, de apenas 2 centímetros de largo, con el nervio central muy visible. De forma silvestre puede alcanzar los 12 metros de altura, aunque en cultivo rara vez se le deja superar los 2 a 3 metros.',
        amount:0,
        stock: 10,
        id: 2
    },
    {
        image: require('../assets/plantas_exterior/Latania_XL.jpg'),
        imageAlt: 'Latania-XL',
        name: 'Latania - XL',
        categoryId: 1,
        price: 999,
        description: 'Palmera de gran tamaño con pecíolos largos con espinas cerca de la base. Hojas grandes con forma de abanico. De muy fácil mantenimiento y muy ornamental gracias a sus grandes hojas.',
        amount:0,
        stock: 10,
        id: 3
    },
    {
        image: require('../assets/plantas_exterior/BuxusBocha_M.jpg'),
        imageAlt: 'Buxus Bocha',
        name: 'Buxus Bocha – M',
        categoryId: 1,
        price: 999,
        description: 'Es un arbusto de follaje perenne, podado con forma de bocha. Crece lentamente, y hay que podarlo al menos 2 veces al año para darle forma. Resiste cualquier condición de cultivo, siempre que esté en exterior y no se riegue excesivamente. Resiste sombra y riegos moderados.',
        amount:0,
        stock: 10,
        id: 4
    },
    {
        image: require('../assets/plantas_exterior/EvonimusMaculata_M.jpg'),
        imageAlt: 'Evonimus maculata',
        name: 'Bvonimus maculata – M',
        categoryId: 1,
        price: 999,
        description: 'Arbusto muy compacto, crece lentamente. Se puede podar para dar forma. Resiste sol, viento, y riegos moderados. ´Aureus´ y ´Aureomarginatus´ tienen las hojas variegadas de amarillo. ´Kathy´ tiene las hojas variegadas con blanco.',
        amount:0,
        stock: 10,
        id: 5
    },
    {
        image: require('../assets/plantas_exterior/CactusEspiralado_M.jpg'),
        imageAlt: 'Cactus espiralado',
        name: 'Cactus espiralado – M',
        categoryId: 1,
        price: 999,
        description: 'Su color azul verdoso y su forma columnar en espiral es algo fuera de lo común y muy fácil de cuidar.',
        amount:0,
        stock: 10,
        id: 6
    },
    {
        image: require('../assets/plantas_exterior/DieteBicolor_M.jpg'),
        imageAlt: 'Diete Bicolor',
        name: 'Diete Bicolor – M',
        categoryId: 1,
        price: 999,
        description: 'Es una planta herbácea cuyas hojas son en forma de cinta, de color verde claro y que pueden alcanzar casi un metro de altura. Durante la primavera y el verano dan hermosas flores terminales de un tono muy claro de amarillo. #FaitfulTip: si se las retiramos ni bien se secan, favoreceremos una próxima y más abundante floración.',
        amount:0,
        stock: 10,
        id: 7
    },
    {
        image: require('../assets/plantas_exterior/DracaenaIndivisaRubra_XL.jpg'),
        imageAlt: 'Dracaena indivisa rubra',
        name: 'Dracaena indivisa rubra – XL',
        categoryId: 1,
        price: 999,
        description: 'Las indivisa son arbustos con hojas semejantes a hojas de palmera , perennes (tienen follaje todo el año). Se plantan como ejemplar singular, en grupos de tres y además en macetas como planta de interior. Da un toque exótico al jardín. Crecen rápido y de manera vigorosa.',
        amount:0,
        stock: 10,
        id: 8
    },
    {
        image: require('../assets/plantas_exterior/DracaenaIndivisaVerde_XL.jpg'),
        imageAlt: 'Dracaena indivisa verde',
        name: 'Dracaena indivisa verde – X',
        categoryId: 1,
        price: 999,
        description: 'Las indivisa son arbustos con hojas semejantes a hojas de palmera , perennes (tienen follaje todo el año). Se plantan como ejemplar singular, en grupos de tres y además en macetas como planta de interior. Da un toque exótico al jardín. Crecen rápido y de manera vigorosa.',
        amount:0,
        stock: 10,
        id: 9
    },
    {
        image: require('../assets/plantas_interior/Aglaonema_S.jpg'),
        imageAlt: 'Aglaonema',
        name: 'Aglaonema – S',
        categoryId: 2,
        price: 999,
        description: 'La Aglaonema es conocida por su atractivo follaje llamativo. Hojas largas de color verde gris azulado. Soportan una amplia gama de condiciones de iluminación interior, desde bajas a brillantes indirectas. Al regar, dejar que los 4 cm superiores de tierra se sequen por completo.',
        amount:0,
        stock: 10,
        id: 10
    },
    {
        image: require('../assets/plantas_interior/AlocasiaCuculata_M.jpg'),
        imageAlt: 'Alocasia Cuculata',
        name: 'Alocasia Cuculata – M',
        categoryId: 2,
        price: 999,
        description: 'La Alocasia Cucullata es una planta que tiene mucho estilo y personalidad. Posee unas hojas de gran tamaño definidas por líneas firmes. Su color y su aspecto tropical la hacen una planta única. Sus hojas pecioladas tienen tonos verdes remarcados por sus nervios también de un verde intenso. Son brillantes y anchas, y miden aproximadamente unos 30 cm de largo.',
        amount:0,
        stock: 10,
        id: 11
    },
    {
        image: require('../assets/plantas_interior/Areca_L.jpg'),
        imageAlt: 'Areca',
        name: 'Areca – L',
        categoryId: 2,
        price: 999,
        description: 'Una planta de 2 metros de altura transpirará por sus hojas en 24 horas una media de 1 litro de agua, por lo que es exigente en cuanto al agua de riego. Siempre ha de mantenerse el cepellón húmedo, aunque sin excesos. Es habitual que las puntas de las hojas adquieran tonos marrones, es señal de que no tiene la suficiente humedad ambiental. Para evitar las puntas marrones hay que pulverizar las hojas con regularidad.',
        amount:0,
        stock: 10,
        id: 12
    },
    {
        image: require('../assets/plantas_interior/AspleniumNidus_S.jpg'),
        imageAlt: 'Asplenium nidus',
        name: 'Asplenium – M',
        categoryId: 2,
        price: 999,
        description: 'Es el helecho más resistente que existe. Esta planta puede tolerar niveles de luz más bajos y riegos menos frecuentes a pesar de sus orígenes subtropicales. Como la mayoría de los helechos, disfruta de una alta humedad y lo ideal es pulverizarlo regularmente.',
        amount:0,
        stock: 10,
        id: 13
    },
    {
        image: require('../assets/plantas_interior/BegoniaRex_M.jpg'),
        imageAlt: 'Begonia Rex',
        name: 'Begonia Rex – M',
        categoryId: 2,
        price: 999,
        description: 'Necesita un lugar luminoso, pero sin sol directo, y un ambiente húmedo y ventilado, pero fuera de las corrientes de aire. Su temperatura óptima es de 18 a 20º; si hace más calor las hojas se abarquillan y se secan. Al regarla no se deben mojar las hojas.',
        amount:0,
        stock: 10,
        id: 14
    },
    {
        image: require('../assets/plantas_interior/CalatheaCtenanthe_S.jpg'),
        imageAlt: 'Calathea Ctenanthe',
        name: 'Calathea Ctenanthe – S',
        categoryId: 2,
        price: 999,
        description: 'Tienen sus hojas dibujadas y parecen pintadas a mano, con líneas, colores rosas, verdes claro, y morados bien intensos. Prefieren espacios húmedos, sin calefacción ni aire acondicionado. Necesitan buena luz indirecta, aunque toleran poca luz, y riego cuando el sustrato esté recién seco.',
        amount:0,
        stock: 10,
        id: 15
    },
    {
        image: require('../assets/plantas_interior/Raphis_L.jpg'),
        imageAlt: 'Raphis',
        name: 'Raphis – M',
        categoryId: 2,
        price: 999,
        description: 'Esta llamativa palmera es un maravilloso punto focal en cualquier habitación. No sólo es decorativa, sino que también es muy resistente e ideal para cualquier espacio.',
        amount:0,
        stock: 10,
        id: 16
    },
    {
        image: require('../assets/plantas_interior/SansevieriaVerde_M.jpg'),
        imageAlt: 'Sansevieria verde',
        name: 'Sansevieria verde – M',
        categoryId: 2,
        price: 999,
        description: 'Sansevieria o llamada también espada de San Jorge se nutre de la negligencia, habiéndose ganado su apodo como la planta “imposible de matar”. Sin embargo, es sensible al riego excesivo, lo que puede hacer que esta planta se pudra.',
        amount:0,
        stock: 10,
        id: 17
    },
    {
        image: require('../assets/plantas_interior/AspleniumNidus_S.jpg'),
        imageAlt: 'Asplenium nidus',
        name: 'Asplenium nidus – S',
        categoryId: 2,
        price: 999,
        description: 'Es el helecho más resistente que existe. Esta planta puede tolerar niveles de luz más bajos y riegos menos frecuentes a pesar de sus orígenes subtropicales. Como la mayoría de los helechos, disfruta de una alta humedad y lo ideal es pulverizarlo regularmente.',
        amount:0,
        stock: 10,
        id: 18
    },
    {
        image: require('../assets/plantas_interior/Raphis_L.jpg'),
        imageAlt: 'Raphis',
        name: 'Raphis – L',
        categoryId: 2,
        price: 999,
        description: 'Esta llamativa palmera es un maravilloso punto focal en cualquier habitación. No sólo es decorativa, sino que también es muy resistente e ideal para cualquier espacio.',
        amount:0,
        stock: 10,
        id: 19
    }
]
